### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by RigoHoward** [networkfusion/alt64#24]
Hello networkfusion, i installed the scripts and libraries and when i try to compile altra64 i got this error:

$ make
/usr/local/bin/mips64-elf-ld -o ./bin/OS64.elf  -O1 -L/usr/local/lib -L/usr/local/mips64-elf/lib -ldragon -lmikmod -lmad -lyaml -lc -lm -ldragonsys -lnosys  -Tn64ld.x
/usr/local/mips64-elf/lib/libdragon.a(entrypoint.o): In function `loadintvectorloop':
(.boot+0x138): reference to `main' not defined
make: *** [Makefile:42: OS64.elf] Error 1

There is something im doing wrong?

**Comment by networkfusion** [comment]
It has been a long time since I last installed this and it is very likely that improvements to WSL or a dependent lib have caused an issue. I plan on updating the install scripts to be fully windows compatible as I now have all dependent libs working fine with windows (see my n64-tools org on github). It will be a few weeks before I get to it though, so feel free to contribute improvements / fixes.

**Comment by RigoHoward** [comment]
Hey networkfusion, many thanks for your quick reply. 

I have to admit that my knowledge compiling for n64 is very limited, so isn't trivial to me to find the cause (but i still trying to figure out what it's going on)

BTW i tried over windows and ubuntu with no luck, and i already check that i can actually compile n64 sources (ie alt64) so it seems my environment its ok.

It's so good to know you have interest on continue your great work! Hoping to see neweer versions of altra64 :)

**Comment by networkfusion** [comment]
Cutting a long story short, it seems that the makefiles `wildcard` function doesnt work on all systems (missing dependency?)... the workaround is to include all SRC files explicitly. I am looking for a solution, but might take a while!

**Comment by RigoHoward** [comment]
Wow, hey!!

Thats unexpected :o, so more references needed right?!

Well it would be nice a workaround of it, thanks for keep an eye on it :)

**Comment by networkfusion** [comment]
If you check out the `ci-cd` branch, I have it building on my local machine, and no longer needs WSL.
Although it builds (on my machine), I am not sure whether it will work due to compile warnings (although I am quite sure they were there before I started on that) so be sure to try it (follow the new readme) and let me know how it works out...

**Comment by RigoHoward** [comment]
Oh yeah i can see your PR, but i cant run your powershell script (i try all the set-executionpolicy commands)
I wil try to download manually the 5 dependencies and see if i can update everything.

edit: i got the updated files and got this error on make:

```
-O1 -L/usr/local/lib -L/usr/local/mips64-elf/lib -ldragon -lmikmod -lmad -lyaml -lc -lm -ldragonsys -lnosys  -Tn64ld.x
C:\cygwin\usr\local\bin\mips64-elf-ld.exe: cannot find -ldragon
C:\cygwin\usr\local\bin\mips64-elf-ld.exe: cannot find -lmikmod
C:\cygwin\usr\local\bin\mips64-elf-ld.exe: cannot find -lmad
C:\cygwin\usr\local\bin\mips64-elf-ld.exe: cannot find -lyaml
C:\cygwin\usr\local\bin\mips64-elf-ld.exe: cannot find -lc
C:\cygwin\usr\local\bin\mips64-elf-ld.exe: cannot find -lm
C:\cygwin\usr\local\bin\mips64-elf-ld.exe: cannot find -ldragonsys
C:\cygwin\usr\local\bin\mips64-elf-ld.exe: cannot find -lnosys
make: *** [Makefile:42: OS64.elf] Error 1
```

**Comment by networkfusion** [comment]
It looks like you haven't extracted the toolchain and libs to the correct locations, and going by the above, you are trying to do this on Linux, where as I have only tested on windows...

**Comment by RigoHoward** [comment]
Yeah i f*ck*d up the directories, because i was trying a mix of cygwin and cmd on Windows 10, i redo the installation and now finally i get it compiling! 

Thank you!

**Comment by networkfusion** [comment]
Closing as moving to dev containers.
