### ISSUE TITLE
Issue with EEPROM filesizes

### ISSUE THREAD

**Issue by gameblabla** [networkfusion/alt64#28]
https://github.com/networkfusion/altra64/blob/master/inc/rom.h#L133

Shouldn't SAVE_SIZE_EEP4k and SAVE_SIZE_EEP16k be 512 and 2048 rather than 4096 and 16384 ? (bits/bytes)

**Comment by networkfusion** [comment]
Quite possibly (I am not the original author of that code)… Can you test and submit a pull request?

**Comment by gameblabla** [comment]
Opened a pull request here : https://github.com/networkfusion/altra64/pull/29

Sadly i can't test because building the toolchain using either your script or upstream's libdragon isn't working for me on linux. Bummer. Would be nice if you make a new release or something with my changes.

**Comment by networkfusion** [comment]
Ok... are you on the latest master? Also one of the branches is nearly ready that has full compatibility  with windows! I just need to get the dependent libs working!!! Otherwise it is a waiting game...

**Comment by gameblabla** [comment]
Yes, latest master. I also tried your branch but that doesn't seem to fix the issue with libmad and libyaml not building due to missing makefile or something ? (i believe that's what you are talking about when you said dependent libs)

**Comment by gameblabla** [comment]
Alright, i managed to get it to compile (with several unrelated changes) on my ED64P and it seems that it is indeed correct.
There's one game, Custom Robo v2, that would refuse to save properly no matter what but i believe that the stock altra64 also suffers from this issue and might not be related ?
Everything else i tried, even Custom Robo v1, worked.

**Comment by networkfusion** [comment]
I have made major strides with the CI-CD branch, to which the rom now compiles (using only windows 10) with GCC 9.2, but I am still stuck on a couple of warnings (which would also affect the version in the master branch). Any help on those would be of great benefit (as well as reviewing the changes already made).

**Comment by networkfusion** [comment]
Fixed.
