### ISSUE TITLE
[WSFL] Sudo perms not passed to setup-linux.sh, other issues (build toolchain fails)

### ISSUE THREAD

**Issue by Drakonas** [networkfusion/alt64#34]
The Toolchain build fails on WSFL, when doubleclicking the setup-wsfl.cmd script.

I was able to get it to get further when I opened a WSL CLI, went to the tools folder, then ran `sudo bash ./setup-linux.sh`.

It seems the setup-wsfl doesn't pass sudo perms to the bash script, thus a lot of commands fail, including collecting the tarballs, running apt update/upgrade, and installing the dependencies to the directed install folder.

But it still fails at this point:

![Screenshot](http://mars.whatbox.ca:42424/img/WindowsTerminal_2021-02-16_14-16-13.png)

**Comment by Drakonas** [comment]
I was able to get further. I believe I was missing the N64 install environment being exported prior to running ./configure.

However, I came across this:
![SS2](http://mars.whatbox.ca:42424/img/WindowsTerminal_2021-02-16_14-32-18.png)

Removing --fforce-mem from that command in the Makefile let it compile. --fforce-addr already exists.

**Comment by Drakonas** [comment]
It would also seem that I didn't notice that libdragon failed. Does your script not do any error checking to be sure the previous build succeeded?

Not sure what to do here.

![SS3](http://mars.whatbox.ca:42424/img/WindowsTerminal_2021-02-16_14-50-46.png)

**Comment by Drakonas** [comment]
Adding `-fpermissive` to the compiler flags lets it complete the make for gcc (pass 1).

This is also required for gcc (pass 2).

I used this to automatically add the flag to line 261 for both pass 1 and 2: (Kind of dirty, but it works. It replaces the entire line)
`sed -i '261s#.*#NO_PIE_CFLAGS = -fno-PIE -fpermissive#' gcc/Makefile`

For reference, the line used to be `NO_PIE_CFLAGS = -fno-PIE`

This has to be done manually after `make` has started and the error is shown, as the gcc folder and its contents aren't created until the make is started. I'm unsure how to get it added pre-compile.'

After all this, I was able to get it compiled successfully and I was able to build the OS64.v64 binary.

**Comment by networkfusion** [comment]
Hi, Given that you are using a V3, you might want to use http://krikzz.com/forum/index.php?topic=7991.0 instead (also written by me), which offers major advantages over AltraOS.

I started working on the issues with the build pipeline here:
https://github.com/networkfusion/altra64/tree/develop-cicd but as you say causes the hang on startup.

Also, the build procedure was on WSL1 and the changes between that and WSL2 are probably the main reasons for the errors above.

I will hopefully come back to AltraOS (for X7 support) in the future, but it is not a priority right now.

**Comment by networkfusion** [comment]
Also, feel free to create a PR if any of your new found knowledge can improve on that in the CICD branch...

**Comment by Drakonas** [comment]
I can see if I can find a way to have this modified to work. Not sure if I can though. I'll have to see if there is a configure paramater to pass the flags or something.

I figured that WSL2 was the reason I was having trouble, to be honest.

To be honest, I mainly did this for a friend who has a ED64 2.5. I have a 64Drive HW2. So this probably won't work. (Nor do I think it is wise to try. :P)

**Comment by Drakonas** [comment]
I added a PR with a couple important changes. The develop-cicd branch actually works for the most part, but it has a compile failure due to missing arguments. I think this is not a WSL issue, but an actual code issue.

**Comment by networkfusion** [comment]
Closing as moving to dev containers.
