### ISSUE TITLE
No sound in some Super Mario 64 hacks

### ISSUE THREAD

**Issue by Sunlitspace542** [networkfusion/alt64#39]
I would have reported this in gameblablabla's fork for ED64P, but there is no issue tab there, and this may be an issue on this codebase as well.

The hacks that I have experienced sound issues with (there could be more):
Peach's Fury
Mario's Vacation Course

After some research, I realized these hacks both used streamed (digital) audio. that may be the issue.

To note: no, I cannot switch to the factory ED64P firmware, as trying to load any rom results in a "rom load error: 103" error.
when switching to an older version of alt64, loading these hacks on that results in working audio.
if it helps at all my ED64P is the more recent MicroSD model, which does not have a USB port.

**Comment by networkfusion** [comment]
Closing as a ROM "HACK" issue.
